version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - public:/public
        depends_on:
            - app

    app:
        build: .
        expose:
            - 80
        environment:
            - DEBUG=False
            - SECRET_KEY=/secretkey.txt
        volumes:
            - public:/public


volumes:
    public:
